### PR TITLE
update eslint

### PR DESCRIPTION
**Pull request by bsr203**

### CODE REVIEW

**Comment by vslinko** [comment]
Is it working? I remember it was broken when I did massive update.

**Comment by chicoxyzzy** [comment]
I assume this is cause airbnb styleguide doesn't use babel-eslint as parser anymore. But this PR handles this so it should be fine. LGTM :)

**Comment by vslinko** [comment]
@chicoxyzzy What are you doing here? :smile:

**Comment by vslinko** [comment]
@bsr203 Thank you for your contribution.

**Comment by chicoxyzzy** [comment]
@vslinko just watching

**Pull request merged**
