### PR TITLE
DO NOT MERGE: support unit test

### PR DESCRIPTION
**Pull request by bsr203**
since the components uses relative path from `frontend` for local imports through webpack alias, simple babel+mocha build fails. Bot sure there a config or need a webpack loader.

### CODE REVIEW

**Comment by vslinko** [comment]
For unit test I'm using karma+webpack+jasmine.

Here you can see my configuration for karma+webpack+mocha: https://github.com/vslinko/template/tree/karma

**Comment by bsr203** [comment]
thanks.. I will try it out and get back to u.

**Comment by bsr203** [comment]
Hi. I found that using Karma was bit slow (forgot the timing but was 2 -4 sec) and mocha was quite fast. Like in this pull request, it is quite lightweight by not involving webpack so I have to turn off some of the features in testing (alias import, less/css import). This may not be ideal for everyone. I close this now till I found a better way to do this. thanks.

**Comment by vslinko** [comment]
Hi. I'll work on tests support in next two weeks, so stay tuned.

**Pull request closed without merging**
