### PR TITLE
Upgrading to Babel6

### PR DESCRIPTION
**Pull request by vslinko**
# TODO
- [ ] `./bin/load_fixtures` requires code from `src/graphql`
- [ ] `./bin/update_schema` requires code from `src/graphql`
- [ ] wait for https://github.com/babel/babel/pull/3160
# Upgrade instructions

After merging `ripster` with babel6 support you should review all your codebase:
- Replace `babel/polyfill` to `babel-polyfill`.
- Replace `babel-core/register` to `babel-register`.
- Replace `await*` to `await Promise.all()`.
- Replace `require()` to `require().default`.

### CODE REVIEW

**Comment by yankouskia** [comment]
I consider it's better to use Promise.map (bluebird) instead of (Promise.all + map)

**Comment by vslinko** [comment]
@yankouskia I don't like to use external libraries in cases when it could be done by standard API.

**Comment by bsr203** [comment]
@vslinko are there conflicts with packages which prevent from using babel6.

**Comment by vslinko** [comment]
Waiting for https://github.com/facebook/relay/pull/889 to release

**Comment by bsr203** [comment]
yup. I made that (2 lines) change locally to try out. 

in babel-relay-plugin/lib/babelAdapter.js

add line 18:  var babel = require('babel-core');
change line 22:   if (Plugin == null || /^6./.test(babel.version)) {

**Pull request closed without merging**
